language: java
before_install:
- openssl aes-256-cbc -K $encrypted_d4dfddbc6378_key -iv $encrypted_d4dfddbc6378_iv
  -in deploy.enc -out deploy -d
script:
- mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: c8/RdARjgWRdF7q5CTNOQnMtN/iq3q0m2B4v7cG9mVUULe+sLW/J1cEypmnTwShFmo5SKHIn6PmCXU1GKf3umF6rQO8dZo6dY9TU80SnfFl6PR6QBRmlY+QOfN8zbmN8P1QAJhWA/Ufvx1gW9perWG+oChaBHKKcCt3tF7i5g13z+wFJJwCskPctPyz2/BNlzpzOLD2npjP2pMTE7EHSFQ0u3yeDSfzmBgA/LLq7nFvpbr4o5/+0HHf0AzuznkyB7sYlrcv5p6Tkp7x638dD1x1jnU95CbsNzlaXK8JZ9QML6Wn/b0tNCUwaZAwzoLU4JFvR3GXq9O6gkeOjGMrILcVolr8PgosGII3tQuf2ydMHCDMxEBQzmrmp7mzNf22E+wJyBXF5lBnQW21tgP2fn0yeNvG3p+A4lDl6KOzk+H5jFpYxE8eXuU4WJw8hHrdpmBp8LMNBrAG06HdPE8DHv0AYcwKph/ICSpW2byZFcxRDVGRSwL9nvksd/dse/u2ZxUjP5UztTagSc527NF7TqZd9rKTU6ztBTMMJCcQZjPVbN/gL+2lCz15oGqF+kPRxVrK0BSP4+Ec+K6bJCYEqCqGnC3lrXe90B3KVGOxDLVv5rirVJ1Lpb5CEnsMRgEokfK/6LyAYa4H77mt4d/ShRBLtMorHx9IAVFOu4vqJS30=
  app: telegramprueba
  on:
    repo: EGC-G2-Trabajo-1718/Cabina-Telegram
